version: '3.8'
services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=notificationservice
      - POSTGRES_USER=notificationservice-rw
      - POSTGRES_PASSWORD=notificationservice-rw
    ports:
      - '5435:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local